// <auto-generated />
using System;
using CTCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTCore.Data.Migrations
{
    [DbContext(typeof(CtCoreDbContext))]
    [Migration("20181231223045_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CTCore.Domain.ClassType", b =>
                {
                    b.Property<int>("ClassTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.HasKey("ClassTypeId");

                    b.ToTable("ClassType");
                });

            modelBuilder.Entity("CTCore.Domain.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.HasKey("InstructorId");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("CTCore.Domain.StudentClass", b =>
                {
                    b.Property<int>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassTypeId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<int>("InstructorId");

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<DateTime>("LastTestDate");

                    b.Property<string>("Rank")
                        .HasMaxLength(20);

                    b.Property<DateTime>("TkdBod");

                    b.HasKey("StudentClassId");

                    b.HasIndex("ClassTypeId");

                    b.HasIndex("InstructorId");

                    b.ToTable("StudentClass");
                });

            modelBuilder.Entity("CTCore.Domain.StudentClass", b =>
                {
                    b.HasOne("CTCore.Domain.ClassType")
                        .WithMany("StudentClassesList")
                        .HasForeignKey("ClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CTCore.Domain.Instructor")
                        .WithMany("ScList")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
